---
- name: remi-repo template 
  template:
    src: templates/remi.repo.j2 
    dest: /etc/yum.repos.d/remi.repo 
    mode: 0644

- name: upgrade php 
  shell: yum update php* -y 

- name: restart varnish
  service: 
    name: "{{ item }}"
    state: restarted
  with_items:
    - httpd
    - varnish
