---
- name: wordpress update
  command: /usr/local/bin/wp core update
  args:
    chdir: "{{ docroot }}"

- name: plugin updates
  command: /usr/local/bin/wp plugin update --all
  args:
    chdir: "{{ docroot }}"
  ignore_errors: yes
