---
- name: copy move_nginx_files script
  template:
    src: roles/ssl_restore/templates/move_nginx_files.sh.j2
    dest: ~/move_nginx_files.sh
    owner: root
    group: root
    mode: 0755

#- stat: path=etc/
#  register: mvnginx

- name: move files
  command: sh ~/move_nginx_files.sh
#  when: mvnginx.stat.exists

- name: start and enable nginx
  service: name=nginx state=started enabled=yes
