---
- replace:
    dest: /etc/varnish/varnish.params
    regexp: 'VARNISH_LISTEN_PORT=80'
    replace: "VARNISH_LISTEN_PORT={{ varnish_port }}"

- name: restart varnish
  service: name=varnish state=restarted
