---
- name: create wordpress database
  mysql_db:
    name: "{{ database }}"
    state: present

- mysql_user:
    name: "{{ wordpress_user }}"
    host: localhost 
    password: "{{ wordpress_user_mysql_password }}"
    priv: '{{ database }}.*:ALL,GRANT'
    state: present
