---
- name: Download wp-cli
  get_url:
      url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      dest: /home


- stat: path=/usr/local/bin/wp
  register: wp

- name: Move wpcli to bin
  command: mv /home/wp-cli.phar /usr/local/bin/wp
  when: not wp.stat.exists

- name: change permissions to executable
  file: path=/usr/local/bin/wp owner=root group=root mode=755
